name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: JoaoCustodio66

      - name: Criar Pasta para a Animação
        run: mkdir -p output

      - name: Copiar Animação para a Pasta de Output
        run: cp dist/github-contribution-grid-snake.svg output/github-contribution-grid-snake.svg

      - name: Commit e Push da Animação
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Atualiza animação da cobrinha"
          git push
